### ISSUE TITLE
open jksm arm11 error

### ISSUE THREAD

**Issue by heiyu-04** [J-D-K/JKSM#57]
I build "JK's save Manager - 7.27.2021" but However, an ARM11 error will be reported after reading the data

**Comment by J-D-K** [comment]
Does it write the cache or not even make it there? I was experimenting with having generated icons like switch but it's not 100% stable.

**Comment by TuxSH** [comment]
It doesn't get there AFAIK, crash at "Loading Titles"

```
#0  0x0012de4c in C3D_FrameDrawOn (target=0x0) at /home/fincs/git/pacman-packages/citro3d/src/citro3d-1.7.0/source/renderqueue.c:183
#1  0x0011e3d0 in C2D_SceneBegin (target=0x0) at /opt/devkitpro/libctru/include/c2d/base.h:295
#2  0x0011f764 in util::createIconGeneric (txt=..., sub=0x213010 <gfx::iconSubTex>) at /mnt/c/git/misc/JKSM/src/util.cpp:235
#3  0x001061a0 in data::titleData::init (this=0x819f300, _id=@0x81d7538: 0x400300000c502, mt=@0x819f3fb: MEDIATYPE_NAND) at /mnt/c/git/misc/JKSM/src/data.cpp:201
#4  0x0010722c in data::loadTitles (a=0x810ea10) at /mnt/c/git/misc/JKSM/src/data.cpp:446
#5  0x001b85f0 in _thread_begin (arg=0x818f008) at /mnt/c/git/libctru/libctru/source/thread.c:21
#6  0x00000000 in ?? ()
```

```
icnTarget = 0x0
txtX = 0x8
ret = 0x810ec90
```

**Comment by J-D-K** [comment]
It's probably a thread or data race issue. It's been a while since I looked and I don't have a lot of time to do it lately. I remember my whole main thread updates the screen while tasks run in other threads idea that works on switch didn't make the jump to 3DS too well. I only remember that it must've been somewhat stable for me, because I do remember using it to test Google drive before life got in the way.
